export const SHOW_FORM_ADD_PARKING = 'SHOW_FORM_ADD_PARKING'
export const CANCLE_FORM_ADD_PARKING = 'CANCLE_FORM_ADD_PARKING'
export const EDIT_FORM_DATA = 'EDIT_FORM_DATA'
export const IS_ADDING_PARKING = 'IS_ADDING_PARKING'
export const IS_EDITTING_PARKING = 'IS_EDITTING_PARKING'
export const SHOW_INFOWINDOW = 'SHOW_INFOWINDOW'
export const CANCLE_INFOWINDOW = 'CANCLE_INFOWINDOW'
export const MANAGE_PARKING={
    GET_MANAGE_PARKING_REQUEST:'GET_MANAGE_PARKING_REQUEST',
    GET_MANEGE_PARKING_FAILED:'GET_MANEGE_PARKING_FAILED',
    GET_MANAGE_PARKING_SUCCESS:'GET_MANAGE_PARKING_SUCCESS',

    ADD_MANAGE_PARKING_REQUEST:'ADD_MANAGE_PARKING_REQUEST',
    ADD_MANAGE_PARKING_SUCCESS:'ADD_MANAGE_PARKING_SUCCESS',
    ADD_MANAGE_PARKING_FAILED:'ADD_MANAGE_PARKING_FAILED',

    DELETE_MANAGE_PARKING_REQUEST:"DELETE_MANAGE_REQUEST",
    DELETE_MANAGE_PARKING_SUCCESS:"DELETE_MANAGE_PARKING_SUCCESS",
    DELETE_MANAGE_PARKING_FAILED:'DELETE_MANAGE_PARKING_FAILED',

    EDIT_MANAGE_PARKING_REQUEST:'EDIT_MANAGE_PARKING_REQUEST',
    EDIT_MANAGE_PARKING_SUCCESS:'EDIT_MANAGE_PARKING_SUCCESS',
    EDIT_MANAGE_PARKING_FAILED:'EDIT_MANAGE_PARKING_FAILED'
}