export default {
    FETCH_PROVINCES_REQUEST: 'FETCH_PROVINCES_REQUEST',
    FETCH_PROVINCES_SUCCESS: 'FETCH_PROVINCES_SUCCESS',
    FETCH_PROVINCES_FAILED: 'FETCH_PROVINCES_FAILED',

    FETCH_DISTRICTS_REQUEST: 'FETCH_DISTRICTS_REQUEST',
    FETCH_DISTRICTS_SUCCESS: 'FETCH_DISTRICTS_SUCCESS',
    FETCH_DISTRICTS_FAILED: 'FETCH_DISTRICTS_FAILED',

    FETCH_COMMUNES_REQUEST: 'FETCH_COMMUNES_REQUEST',
    FETCH_COMMUNES_SUCCESS: 'FETCH_COMMUNES_SUCCESS',
    FETCH_COMMUNES_FAILED: 'FETCH_COMMUNES_FAILED',
    CLEAR_PROVINCES: 'CLEAR_PROVINCES',
    CLEAR_DISTRICTS:'CLEAR_DISTRICTS'
}
